version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:\projects\tbb
test: off
configuration:
    - Release
    - Debug
branches:
  only:
    - master
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
install:
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects\tbb
  - cmake -G "%CMAKE_PLATFORM%"
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% tbb.sln
  - ctest -C %Configuration%
